---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/git-url: https://github.com/adityadand/spring-boot-devops.git
    jkube.io/git-commit: d8e7a6b7a84bb973c176570a82aad8a14573e546
    jkube.io/git-branch: master
    jkube.io/scm-url: git@github.com:adityadand/spring-demo-webservices-ci-cd.git
    jkube.io/scm-tag: v0.0.2
  labels:
    app: sprint-boot-devops
    provider: jkube
    version: 0.0.2-SNAPSHOT
    group: sprint-boot-devops
  name: sprint-boot-devops
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sprint-boot-devops
      provider: jkube
      group: sprint-boot-devops
  template:
    metadata:
      annotations:
        jkube.io/scm-url: git@github.com:adityadand/spring-demo-webservices-ci-cd.git
        jkube.io/git-url: https://github.com/adityadand/spring-boot-devops.git
        jkube.io/scm-tag: v0.0.2
        jkube.io/git-commit: d8e7a6b7a84bb973c176570a82aad8a14573e546
        jkube.io/git-branch: master
      labels:
        app: sprint-boot-devops
        provider: jkube
        version: 0.0.2-SNAPSHOT
        group: sprint-boot-devops
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE_URL
              name: mysql-config
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: sprint-boot-devops/sprint-boot-devops:latest
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
